# Python review

Goals:
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific taks in our programs

**NumPy**:
- core library for numerical computing in python
- many other pibraries use NumPy arrays as building blocks
- computations on NumPy are optomized for speed and memory usage

Lets import NumPy with **standard abreviation**

In [1]:
import numpy as np

## Variables

**variable**: a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

# Show the value
a

# Print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
**object** (informally speaking) is a bundle of *properties* and *actions* about something specific

Example:

Object: data frame
Properies: number of rows, names of columns, date created
Actions: selecting a specific row, add a new column

A variable is the name we ive to a specific object  and the same object can be referenced by different variables

In practice, we can often use variable and oject interchangably

## Types

Every object in Python has a **type**. The type tells us what kind of object it is.

We can also call the type of an object the **class** of the object and they both refer to the kind of object we have

In [3]:
print(a)

# Check the type/class of a variable/object by using the 'type' function
type(a)

[[1 1 2]
 [3 5 8]]


In [5]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number. 

In [7]:
print(a[1, 1])

5


## Functions

`print` was our first example of a python **function**.

Functions take in a set of **arguments** and those arguements create an **output**.

argument ~ parameter

We can ask for information about a function by executing `?function`

In [8]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**. 

A function has two types of arugments:

- **non-optional**: arguments *you* need to specify for the function to do something
- **optional**: arguments that are pre-filled with a default value by the function. You can override them. Optional arguments appear inside the parenthesis in the form `optional_argument = default_value`

In [9]:
print('changing the default end argument', end = ' :)')

changing the default end argument:)

## Attributes and Methods

An object in python has attributes and methods

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object

Fish attributes:
- length, color, species
- die(), bite(), stir_fry()

**Example**
Attributes for `numpy.arrays`

We can access a variable's methods and attributes by adding a period at the end of the variable's name

`variable.method()` or `variable.attribute`

In [10]:
a.shape

(2, 3)

In [11]:
type(a.shape)

In [13]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [14]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis = 0)

array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameters:

In [15]:
a.min()

1

Remember: methods are functions associated with an object. 

In [17]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional argument? Why?
2. Create two new variables, one with the integer value 77 and one with the string 99.
3. Use your variables to print `77%99%77` by changing the value of one of the optional argument default values in `print`.

In [18]:
# 1
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [19]:
# 2
my_int = 77
my_str = '99'

# 3
print(my_int, my_str, my_int, sep = "%")

77%99%77
